#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

scope="$1" && shift

case "$scope" in
	"note" | "document" | "doc" )

		title=$(date +"%s")
		notebook="home"
		declare content
		declare tags

		while (( "$#" )); do
			case "$1" in
				"title")
					shift && title="${1%,}" && shift
					;;
				"content")
					shift && content="${1%,}" && shift
					;;
				"tags")
					shift && tags="${1%,}" && shift
					;;
				*) shift ;;
			esac
		done

		b/notes create -T "$title" -C "$content" -t "$tags"

		;;

  *)
	echo "Invalid scope: $scope"
	exit 1
	;;
esac