#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

scope="$1" && shift

case $scope in 
	"assistant" )
		shift && assistant="$1" && shift
		case $1 in
			"name" )
				shift
				case $1 in
					"to" | "as" )
						shift
						;;
					*)
						shift && name="$1" && shift
						;;
				esac
				;;
			"instructions" )
				shift
				case $1 in
					"to" | "as" )
						shift
						;;
					*)
						shift && instructions="$1" && shift
						;;
				esac
				;;
			*)
				shift
				;;
		esac
		;;

	*)
		shift
		;;
esac