#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

scope="$1"

case "$scope" in
	"note" )

		identifier="$2"

		b/notes show "$identifier"

		;;
	* ) b/error "Invalid scope" "$scope" ;;
esac