#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# for both ubuntu and bsd, print today's date in the format YYYY-MM-DD or if $1 = 'friendly' then print it in the format 'Month Day, Year'

if [ "$1" = 'friendly' ]; then
  if [ "$(uname)" = 'Darwin' ]; then
	date "+%B %e, %Y"
  else
	date "+%B %-d, %Y"
  fi
else
  date "+%Y-%m-%d"
fi