#!/usr/bin/env bash

# Change directory to the current script's directory
cd "$(dirname "$0")"

# Source the .env file
[[ -f .etc/barerc ]] && source .etc/barerc

# Temporarily add ./ to PATH
PATH="./:$PATH"

# Delegate the rest
script_name="$1" && shift && ./"$script_name" "$@"