#!/usr/bin/env bash

./deps git

# Change directory to the current script's directory
cd "$(dirname "$0")" || exit

# Setup environment
source .etc/barerc

PATH="./:$PATH"

# check if we need to sync bare
touch .var/sync && {
	now=$(git log -1 --format=%ct)
	[[ $(cat .var/sync) -lt $now ]] && {
		bash .lib/sync && echo "$now" > .var/sync
	}
}

# close up shop early, if that's it
[[ -z $1 ]] && exit 0

# Check if the -I flag is provided for interactive mode

case $1 in

	-[iI]|-[tT]|terminal) # i = interactive / t = terminal

		shift && exec bash --rcfile <(cat << EOF

			source ~/.bashrc
			source .etc/barerc

			# put all bare commands in context
			PATH="$(pwd):\$PATH"

			# mostly for Macs running zsh by default
			export BASH_SILENCE_DEPRECATION_WARNING=1

			GREEN='\\033[0;32m'
			YELLOW='\\033[0;33m'
			GRAY='\\033[2;37m'
			RESET='\\033[0m'

			PS1="🐻 \[\${GREEN}\]\$(basename \$(pwd)) \[\${YELLOW}\]> \[\${RESET}\]"

			printf "\n\${GRAY}entering bare terminal. type exit when ready to leave.\${RESET}\n"

EOF
		);

		;;

	*) script_name="$1" && shift && ./"$script_name" "$@" ;;

esac
