#!/usr/bin/env bash

# Change directory to the current script's directory
cd "$(dirname "$0")"

# Setup environment
touch ~/.bashrc
[[ -f .etc/barerc ]] && source .etc/barerc
PATH="./:$PATH"
export PORT=8282

./sync



# close up shop early, if that's it
[[ -z "$1" ]] && exit 0

# Check if the -I flag is provided for interactive mode
if [[ "$1" == "-I" ]]; then
	shift
	# Start an interactive bash shell with the current environment
	exec bash --rcfile <(echo "
	PS1='🐻 bare > '
	source ~/.bashrc
	PATH=\"$PATH\"
	trap 'bare' DEBUG
	")
fi

script_name="$1" && shift && ./"$script_name" "$@"

exit 0