#!/usr/bin/env bash

[[ -t 0 ]] || input=$(cat)

remaining_args=() && while true; do
	case $1 in
		'') break ;;
		--all) all=1 && shift ;;
		*) remaining_args+=("$1") && shift ;;
	esac
done && set -- "${remaining_args[@]}"

[[ -z $input ]] && input="$*" && shift $#

# if 'all', capitalize all words
echo "$input" |
	(
		[[ -n $all ]] \
		&& transform "$input" --capitalize --all \
		|| transform "$input" --capitalize
	)