#!/usr/bin/env bash

[[ -t 0 ]] || input=$(cat)

remaining_args=() && while [[ $# -gt 0 ]]; do
	case $1 in
		--all) all=1 && shift ;;
		*) remaining_args+=("$1") && shift ;;
	esac
done && set -- "${remaining_args[@]}"

[[ -z $input ]] && input="$*" && shift $#

# if 'all', capitalize all words
[[ -n $all ]] && {
	echo "$input" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2)); print}' && exit 0
}

# or just capitalize the first word
echo "$input" | awk '{first=toupper(substr($1,1,1)) tolower(substr($1,2)); $1=""; print first $0}' && exit 0