#!/usr/bin/env bash

# use command line arguments as dependencies
deps=("$@")

# check each dependency
missing_deps=()
for dep in "${deps[@]}"; do
	if ! command -v "$dep" &> /dev/null; then
		missing_deps+=("$dep")
	fi
done

# if there are any missing dependencies, print them
if [ ${#missing_deps[@]} -ne 0 ]; then
	echo -n "ERROR >> The following dependencies are missing and need to be installed: "
	for index in "${!missing_deps[@]}"; do
		dep=${missing_deps[$index]}
		if (( index == ${#missing_deps[@]}-1 )); then
			printf '%s' "$dep"
		else
			printf '%s, ' "$dep"
		fi
	done
	echo "."
	exit 1
fi