#!/usr/bin/env bash

# check each dependency
missing_deps=()
for dep in "$@"; do
	if ! command -v "$dep" &> /dev/null; then
		missing_deps+=("$dep")
	fi
done

# if there are any missing dependencies, print them
if [ ${#missing_deps[@]} -gt 0 ]; then
	echo "ERROR >> The following dependencies are missing and need to be installed: "
	for i in "${!missing_deps[@]}"; do
		dep=${missing_deps[$i]}
		if (( i == ${#missing_deps[@]}-1 )); then
			printf '%s' "$dep"
		else
			printf '%s, ' "$dep"
		fi
	done && echo "."
	exit 1
fi