#!/usr/bin/env bash

# ideal usage
# ./bare download https://mydownload.com/file.mp3 --title my-title --tags my-tag

./deps curl

[[ -t 0 ]] && { url=$1; shift; } || url=$(cat)

[[ -z $url ]] && echo "No URL provided" && exit 1

[[ $(validate url "$url") == 'false' ]] && echo "Invalid URL" && exit 1

# check if this is a YouTube link
[[ "$(./bare youtube id "$url")" = 'Invalid YouTube URL' ]] && is_youtube=0 || is_youtube=1

# setup environment
output_name="$(./bare random string 32)"
temp_file=".var/downloads/${output_name}"

while true; do # continue through remaining args
  case $1 in
    '') break ;;
    --mp3) as_mp3=1 && shift ;;
    --thumbnail|--thumb) as_thumbnail=1 && shift ;;
    * ) echo "Unknown option: $1" && exit 1 ;;
  esac
done

if [[ "$is_youtube" = 1 ]]; then

    [[ "$as_mp3" ]] && {
        ./bare youtube download "$url" --mp3
        exit 0
    }

    [[ "$as_thumbnail" ]] && {
        ./bare youtube download "$url" --thumbnail --max
        exit 0
    }

    ./bare youtube download "$url"
    exit 0

else

	# Download the file to a temporary location
	./bare request "$url" --output "$temp_file"

	# Determine the MIME type
	mime_type=$(file --mime-type -b "$temp_file")

	# Map MIME type to extension
	declare -A mime_extension_map=(
		["image/png"]="png"
		["image/jpeg"]="jpg"
		["image/gif"]="gif"
		["image/webp"]="webp"
		["audio/mpeg"]="mp3"
		["video/mp4"]="mp4"
		["application/pdf"]="pdf"
		["application/json"]="json"
		["text/markdown"]="md"
		["text/plain"]="txt"
		["text/csv"]="csv"
		["application/zip"]="zip"
		["text/html"]="html"
	)

	extension="${mime_extension_map[$mime_type]}"

	[[ -z "$extension" ]] && echo "Unsupported MIME type: $mime_type" && exit 1

	# Construct the final output file name with the correct extension
	output_file=".var/downloads/${output_name}.${extension}"

	# Rename the file
	mv "$temp_file" "$output_file"

	echo "$output_file"
fi