#!/usr/bin/env bash

# Check if a file argument is provided
[ $# -eq 0 ] && {
	echo "Usage: ./interpret <script-name>"
	exit 1
}

# Ensure script name does not contain path traversal characters
script_title="${1-$(cat)}" && shift

script_contents=$(recsel -t Script .var/scripts.rec -e "Title = '$script_title'" -P Contents)

[[ -z $script_contents ]] && echo "No script by that title found: $script_title" && exit 1

# Prepend shebang and PATH export, then execute the script
{
	printf '#!/usr/bin/env bash\nexport PATH="$PATH:."\n'
	echo "$script_contents"
} | bash -s -- "$@"
