#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

# Check if a file argument is provided
[ $# -eq 0 ] && {
	echo "Usage: ./interpret <script-name>"
	exit 1
}

# Ensure script name does not contain path traversal characters
script_title="${1-$(cat)}" && shift

script_contents=$(cat ".var/scripts/$script_title")
[[ $script_contents == '' ]] && echo "No script by that title found: $script_title" && exit 1

# Create a temporary file
temp_script=$(mktemp)

# Prepend shebang and PATH export, then write the script contents to the temporary file
{
	printf '#!/usr/bin/env bash\nset -e\nexport PATH="$PATH:."\n'
	echo "$script_contents"
} > "$temp_script"

# Make the temporary file executable
chmod +x "$temp_script"

# Execute the temporary script
"$temp_script" "$@"

# Remove the temporary file
rm "$temp_script"
