#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

[ -z "$EDITOR" ] && echo "EDITOR is not set" && exit 1

# Check if $1 is provided
if [ -n "$1" ]; then
	file="$1"
else
	# Read from stdin
	file=$(cat)
fi

"$EDITOR" "$file"