#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

deps qrencode

# Attempt to read from stdin, if nothing is piped in, use $1
if [ -t 0 ]; then
  # Terminal is attached, stdin is not redirected, use $1
  link="$1"
else
  # stdin is redirected, read from stdin
  read -r link
fi

output=".var/downloads/$(./bare random string 30).png"

qrencode -o "$output" "$link"

echo "$output"