#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

function main() {
	
	# Default command
	local command='string'
	local length='16'
	local constraint=''

	# Parse arguments
	while [[ $# -gt 0 ]]; do
		case $1 in
			string|alpha|number) command=$1 ;;
			*) length=$1 ;;
		esac && shift
	done

	# Validate the length
	if [[ ! $length =~ ^[0-9]+$ ]]; then
		echo "Invalid length: $length. Must be a positive integer."
		exit 1
	fi

	# Character sets for each command
	case $command in
		string) constraint='a-zA-Z0-9' ;;
		alpha) constraint='a-zA-Z' ;;
		number) constraint='0-9' ;;
		*) echo "Invalid command: $command" && exit 1 ;;
	esac

	# Generate random string
	LC_ALL=C tr -dc "$constraint" < /dev/urandom | head -c "$length"; echo
	
}

run_script "$@"
