#!/usr/bin/env bash

deps pandoc

function main() {

	# Process arguments to handle flags and content
	args=() && for arg in "$@"; do
		case "$arg" in
			--to-html|--as-html)
				to_html=1 && shift
				;;
			--pretty)
				deps glow
				pretty=1 && shift
				;;
			*) args+=("$arg") && shift ;;
		esac
	done && set -- "${args[@]}"

	content=$1 && shift
	to_html=0

	# Output content, converting to HTML if required
	if [[ $to_html -eq 1 ]]; then
		echo "$content" | pandoc
	elif [[ $pretty -eq 1 ]]; then
		echo "$content" | glow
	else
		echo "$content"
	fi

}

run_script "$@"