#!/usr/bin/env bash

./deps cmark || exit 1

# Initialize flags
[[ -t 0 ]] && content="$(cat ".var/$1")" && shift || content="$(cat)"
to_html=0
inline=0

# Process arguments to handle flags and content
args=()
for arg in "$@"; do
	case "$arg" in
		--to-html|--as-html)
			to_html=1 && shift
			;;
		*)
			args+=("$arg")
			;;
	esac
done

# echo all remaining args
set -- "${args[@]}"

# Output content, converting to HTML if required
if [[ $to_html -eq 1 ]]; then
	eval "echo \"$content\"" | cmark
else
	eval "echo \"$content\""
fi
