#!/usr/bin/env bash

./deps cmark || exit 1

# Initialize flags
file=".var/$1" && shift
to_html=0
inline=0

# Process arguments to handle flags and content
args=()
for arg in "$@"; do
	case "$arg" in
		--to-html)
			to_html=1 && shift
			;;
		*)
			args+=("$arg")
			;;
	esac
done

# echo all remaining args
set -- "${args[@]}"

content=$(< "$file")

# Output content, converting to HTML if required
if [[ $to_html -eq 1 ]]; then
	eval "echo \"$content\"" | cmark
else
	eval "echo \"$content\""
fi
