#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

# Read input from stdin if not provided as an argument

function main() {

	local args script csv

	args=() && while [[ $# -gt 0 ]]; do
		case $1 in
			:over) csv=$2 && shift 2 ;;
			*) args+=("$1") && shift ;;
		esac
	done && set -- "${args[@]}"

	script="$1" && shift

	if [[ -n $csv && -f $csv ]]; then

		csv=$(cat "$csv")

		IFS=',' read -r -a fields <<< "$(echo "$csv" | head -n 1)"

		echo "$csv" | tail -n +2 | while IFS=',' read -r line; do

			IFS=',' read -r -a values <<< "$line"
			
			for ((i=0; i<${#fields[@]}; i++)); do
				field_name="${fields[$i]}"
				field_value="${values[$i]}"
				field_value=$(echo "$field_value" | xargs | sed 's/^"\|"$//g')
				export "$field_name"="$field_value"
			done

			interpret "$script" "$@"

		done

	else

		interpret "$script" "$@"

	fi

}

run_script "$@"
