#!/usr/bin/env bash

./deps sqlpage

# sync files from .lib/www to .var/www without overwriting new files in .var/www
mkdir -p ".var/www" && rsync -av ".lib/www/" ".var/www/" >> /dev/null

export PORT=8282
export allow_exec=true
export max_uploaded_file_size=50000000

command="$1"

case "$command" in

	--briefly )
		./bare serve > /dev/null 2>&1 &
		service_pid=$!

		# Give the service some time to start
		sleep 0.2

		if ps -p $service_pid > /dev/null; then
			kill $service_pid
			wait $service_pid 2>/dev/null
		fi
		;;

	* )
		cd .var/www && sqlpage
		;;
esac

exit 0