#!/usr/bin/env bash

cd "$(dirname "$0")" && source .lib/barerc || exit 1

function main() {

	[[ -t 0 ]] && input=$1 || input=$(cat)

	# catch no input && exit
	[[ -n $input ]] || { echo "No input provided"; exit 1; }

	echo "$input"
	
}