#!/usr/bin/env bash

find "$1" -type f -exec stat -f%z {} + | awk '{
	total += $1
}
END {
	if (total >= 1073741824) 
		printf "%.2f GB\n", total / 1073741824
	else if (total >= 1048576) 
		printf "%.2f MB\n", total / 1048576
	else if (total >= 1024) 
		printf "%.2f KB\n", total / 1024
	else 
		printf "%d bytes\n", total
}'