#!/usr/bin/env bash

[[ -t 0 ]] || contents=$(cat)

remaining_args=() && while [[ $# -gt 0 ]]; do
	case $1 in
		--to) file="$2" && shift 2 ;;
		--contents) contents="$2" && shift 2 ;;
		*) remaining_args+=("$1") && shift ;;
	esac
done && set -- "${remaining_args[@]}"

[[ $# -eq 1 && -n $file ]] && contents="$1"
[[ $# -eq 1 && -n $contents ]] && file="$1"
[[ $# -eq 2 ]] && { contents="$1"; file="$2"; }

[[ -z $contents ]] && echo "Error: Missing contents" >&2 && exit 1
[[ -z $file ]] && echo "Error: Missing file" >&2 && exit 1

echo "$contents" > "$file"
