#!/usr/bin/env bash

# This is the bare run command file and is used to store global bare
# configuration details. DO NOT sotre your API keys or other user specific
# configuration details here, as they will be overwritten on bare update.

# Define an associative array
declare -A BASE_CONFIG

# Set the values in the associative array
BASE_CONFIG=(
    ["OPENAI_API_KEY"]=""
    ["STRIPE_SECRET_KEY"]=""
    ["POSTMARK_SERVER_TOKEN"]=""
    ["BARE_DIR"]=$(pwd)
    ["BARE_COLOR"]=0
	["BARE_DEBUG"]=0
)

# Loop over the array and export each key-value pair
for key in "${!BASE_CONFIG[@]}"; do
    export "$key"="${BASE_CONFIG[$key]}"
done

# shellcheck disable=SC1091
source "$BARE_DIR/.etc/barerc"
[[ -f ~/.barerc ]] && source ~/.barerc
