#!/usr/bin/env bash

# Primary entry point and initialization for global config.
# DO NOT put your API keys or other user user config here,
# as this file will be overwritten on bare update.

deps git

# Detect macOS, Ubuntu, or Other
OS=$({
	[[ $(uname) == 'Linux' ]] \
		&& grep -q 'Ubuntu' /etc/os-release \
		&& echo "Ubuntu"
	[[ $(uname) == 'Darwin' ]] && echo "macOS"
} || echo "Other") && export OS

# Set the values in the associative array
declare -A BASE_CONFIG && BASE_CONFIG=(
	["BARE_VERSION"]=$(git log -1 --format=%ct)
    ["BARE_DIR"]=$(pwd)
	["BARE_TIMEZONE"]=UTC
    ["BARE_COLOR"]=0
	["BARE_PADDING"]=0
	["BARE_DEBUG"]=0
	["HETZNER_API_TOKEN"]=''
	["DIGITALOCEAN_API_TOKEN"]=''
	["LINODE_API_TOKEN"]=''
	["VULTR_API_TOKEN"]=''
    ["OPENAI_API_KEY"]=''
    ["STRIPE_SECRET_KEY"]=''
    ["POSTMARK_SERVER_TOKEN"]=''
	["TOMORROW_WEATHER_API_KEY"]=''
) && for key in "${!BASE_CONFIG[@]}"; do
    export "$key"="${BASE_CONFIG[$key]}"
done

# check if we need to sync bare
[[ $(cat .var/sync) -lt $BARE_VERSION ]] && {
	bash .lib/sync && echo "$BARE_VERSION" > .var/sync
}

# shellcheck disable=1091
source .etc/barerc
source .lib/functions
